dist: xenial
language: python
python: 3.5
before_install:
  - sudo apt-get update
  - sudo apt-get install libpython3-dev
install:
  - pip3 install -r requirements.txt
  - ./dependencies.sh
script:
  - py.test --cov 
after_success:
  - coveralls
