dist: xenial
language: python
python: 3.5
before_install:
  - sudo apt-get update
  - sudo apt-get install libpython3-dev
install:
  - virtualenv .test
  - .test/bin/pip3 install -r requirements.txt
  - ./dependencies.sh
script:
  - .test/bin/py.test --cov 
after_success:
  - .test/bin/coveralls
