language: python
before_install:
  - sudo apt-get update
  - sudo apt-get install gcc libpython3-dev
python:
  - "3.6"
  - "3.7-dev"
install:
  - pip install -r requirements.txt
script:
  - pytest
services:
  - mongodb
