dist:
  - trusty
  - xenial
language: python
before_install:
  - sudo apt-get update
  - sudo apt-get install libpython3-dev
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest --cov 
services:
  - mongodb
after_success:
  - coveralls
